# Site settings
title: Kiinlam's blog
email: Kiinlam.cheung@gmail.com
description: 又一个前端开发小码农，本博客主要分享原创文章，并与大家分享。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://kiinlam.github.com" # the base hostname & protocol for your site
twitter_username: kiinlam
github_username:  kiinlam
author_info: <a href="https://kiinlam.github.com">Kiinlam</a>

# Build settings
# markdown: kramdown
permalink: /:title
paginate: 8
feed: /feed.xml
markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "autolink", "tables", "strikethrough"]

defaults:
  -
    scope:
      path: "_posts"
    values:
      author: <a href="https://kiinlam.github.com">Kiinlam</a>
      meta: ""