# Site settings
title: Kiinlam's blog
email: Kiinlam.cheung@gmail.com
description: 又一个前端开发小码农，本博客主要分享原创文章，并与大家分享。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.flappyend.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  kiinlam

# Build settings
markdown: kramdown
# highlighter: null