# Site settings
title: Kiinlam's blog
email: Kiinlam.cheung@gmail.com
description: 又一个前端开发小码农，本博客主要分享原创文章，并与大家分享。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.flappyend.com" # the base hostname & protocol for your site
twitter_username: kiinlam
github_username:  kiinlam
author_info: <a href="http://blog.flappyend.com/">Kiinlam</a>

# Build settings
markdown: kramdown
permalink: /:title
paginate: 8
feed: /feed.xml
# highlighter: null

defaults:
  -
    scope:
      path: "_posts"
    values:
      author: <a href="http://blog.flappyend.com/">Kiinlam</a>
      meta: ""